# Generated by Django 3.0.5 on 2020-07-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PercentileThresholds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=32)),
                ('cpu_used_total_p1', models.FloatField()),
                ('cpu_used_total_p2', models.FloatField()),
                ('cpu_used_total_p3', models.FloatField()),
                ('cpu_user_used_p1', models.FloatField()),
                ('cpu_user_used_p2', models.FloatField()),
                ('cpu_user_used_p3', models.FloatField()),
                ('cpu_system_used_p1', models.FloatField()),
                ('cpu_system_used_p2', models.FloatField()),
                ('cpu_system_used_p3', models.FloatField()),
                ('tcp_active_opens_p1', models.FloatField()),
                ('tcp_active_opens_p2', models.FloatField()),
                ('tcp_active_opens_p3', models.FloatField()),
                ('tcp_passive_opens_p1', models.FloatField()),
                ('tcp_passive_opens_p2', models.FloatField()),
                ('tcp_passive_opens_p3', models.FloatField()),
                ('close_wait_count_p1', models.FloatField()),
                ('close_wait_count_p2', models.FloatField()),
                ('close_wait_count_p3', models.FloatField()),
                ('mem_usage_rate_p1', models.FloatField()),
                ('mem_usage_rate_p2', models.FloatField()),
                ('mem_usage_rate_p3', models.FloatField()),
                ('swap_usage_rate_p1', models.FloatField()),
                ('swap_usage_rate_p2', models.FloatField()),
                ('swap_usage_rate_p3', models.FloatField()),
                ('available_memory_p1', models.FloatField()),
                ('available_memory_p2', models.FloatField()),
                ('available_memory_p3', models.FloatField()),
                ('contact', models.CharField(max_length=32)),
                ('contact_email', models.CharField(max_length=64)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
