# Generated by Django 3.0.5 on 2020-08-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warning', '0002_auto_20200719_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thresholds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=32)),
                ('cpu_used_total_t1', models.FloatField(default=0)),
                ('cpu_used_total_t2', models.FloatField(default=0)),
                ('cpu_used_total_t3', models.FloatField(default=0)),
                ('cpu_user_used_t1', models.FloatField(default=0)),
                ('cpu_user_used_t2', models.FloatField(default=0)),
                ('cpu_user_used_t3', models.FloatField(default=0)),
                ('cpu_system_used_t1', models.FloatField(default=0)),
                ('cpu_system_used_t2', models.FloatField(default=0)),
                ('cpu_system_used_t3', models.FloatField(default=0)),
                ('tcp_active_opens_t1', models.FloatField(default=0)),
                ('tcp_active_opens_t2', models.FloatField(default=0)),
                ('tcp_active_opens_t3', models.FloatField(default=0)),
                ('tcp_passive_opens_t1', models.FloatField(default=0)),
                ('tcp_passive_opens_t2', models.FloatField(default=0)),
                ('tcp_passive_opens_t3', models.FloatField(default=0)),
                ('close_wait_count_t1', models.FloatField(default=0)),
                ('close_wait_count_t2', models.FloatField(default=0)),
                ('close_wait_count_t3', models.FloatField(default=0)),
                ('mem_usage_rate_t1', models.FloatField(default=0)),
                ('mem_usage_rate_t2', models.FloatField(default=0)),
                ('mem_usage_rate_t3', models.FloatField(default=0)),
                ('swap_usage_rate_t1', models.FloatField(default=0)),
                ('swap_usage_rate_t2', models.FloatField(default=0)),
                ('swap_usage_rate_t3', models.FloatField(default=0)),
                ('available_memory_t1', models.FloatField(default=0)),
                ('available_memory_t2', models.FloatField(default=0)),
                ('available_memory_t3', models.FloatField(default=0)),
            ],
        ),
    ]
