# Generated by Django 3.0.5 on 2020-08-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Warning', '0004_auto_20200826_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='percentilethresholds',
            old_name='close_wait_count_p1',
            new_name='dev_io_read_rate_p1',
        ),
        migrations.RenameField(
            model_name='percentilethresholds',
            old_name='close_wait_count_p2',
            new_name='dev_io_read_rate_p2',
        ),
        migrations.RenameField(
            model_name='percentilethresholds',
            old_name='close_wait_count_p3',
            new_name='dev_io_read_rate_p3',
        ),
        migrations.RenameField(
            model_name='thresholds',
            old_name='close_wait_count_t1',
            new_name='dev_io_read_rate_t1',
        ),
        migrations.RenameField(
            model_name='thresholds',
            old_name='close_wait_count_t2',
            new_name='dev_io_read_rate_t2',
        ),
        migrations.RenameField(
            model_name='thresholds',
            old_name='close_wait_count_t3',
            new_name='dev_io_read_rate_t3',
        ),
    ]
