# Generated by Django 3.0.5 on 2020-07-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('ip_address', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=20)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
    ]
