# Generated by Django 3.0.5 on 2020-06-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=32)),
                ('cpu_used_total', models.FloatField()),
                ('cpu_user_used', models.FloatField()),
                ('cpu_system_used', models.FloatField()),
                ('cpu_average_5min', models.FloatField()),
                ('cpu_io_wait', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
