# Generated by Django 3.0.5 on 2020-06-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
