# Generated by Django 3.0.5 on 2020-06-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0002_auto_20200623_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
