# Generated by Django 3.0.5 on 2020-06-23 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0003_auto_20200623_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
