# Generated by Django 3.0.5 on 2020-06-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0005_auto_20200624_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
