# Generated by Django 3.0.5 on 2020-06-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0007_network_systemmemory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='tcp_activeopens',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='network',
            name='tcp_passiveopens',
            field=models.IntegerField(),
        ),
    ]
