# Generated by Django 3.0.5 on 2020-06-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0008_auto_20200625_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpu',
            options={'ordering': ['time']},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ['time']},
        ),
        migrations.AlterModelOptions(
            name='systemmemory',
            options={'ordering': ['time']},
        ),
    ]
