# Generated by Django 3.0.5 on 2020-06-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0009_auto_20200626_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemmemory',
            old_name='available_memeory',
            new_name='available_memory',
        ),
    ]
