# Generated by Django 3.0.5 on 2020-07-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0010_auto_20200626_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='tcp_activeopens',
            new_name='tcp_active_opens',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='tcp_passiveopens',
            new_name='tcp_passive_opens',
        ),
    ]
