# Generated by Django 3.0.5 on 2020-08-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0012_auto_20200826_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='dev_io_read_rate',
            new_name='close_wait_count',
        ),
    ]
