# Generated by Django 3.0.5 on 2020-08-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0013_auto_20200826_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='close_wait_count',
            new_name='dev_io_read_rate',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='tcp_active_opens',
            new_name='dev_io_usage_rate',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='tcp_passive_opens',
            new_name='dev_io_write_rate',
        ),
    ]
