# Generated by Django 3.0.5 on 2020-06-21 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户信息表', 'verbose_name_plural': '用户信息表'},
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_id',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AlterModelTable(
            name='users',
            table='user',
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=60)),
                ('username', models.OneToOneField(max_length=32, on_delete=django.db.models.deletion.DO_NOTHING, to='User.Users')),
            ],
            options={
                'verbose_name': '用户token表',
                'verbose_name_plural': '用户token表',
                'db_table': 'user_token',
            },
        ),
    ]
