# Generated by Django 3.0.5 on 2020-06-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20200621_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.IntegerField(verbose_name='用户密码'),
        ),
    ]
