# Generated by Django 3.0.5 on 2020-07-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20200621_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='用户id'),
        ),
    ]
